### ISSUE TITLE
"TypeError: Cannot read property 'properties' of undefined' 

### ISSUE THREAD

**Issue by dwjohnston** [pmadruga/myUI#5]
Out of the box, yarn install, yarn start work fine, I get this issue with yarn build. 

```
/home/david/git-workspace/myUI/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/david/git-workspace/myUI/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/david/git-workspace/myUI/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/david/git-workspace/myUI/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

```

**Comment by WTFlay** [comment]
Update your dependencies.
Ref to #4
